server:
  enabled: true
  address: "0.0.0.0"
  port: 24879
  allow_origin: "http://localhost:5173"

audio_backend: "pulseaudio"
audio_device: "default"
bitrate: 320

device_name: 'SonoakAmp'
device_type: speaker
initial_volume: 100
external_volume: true

normalisation_pregain: 0
normalisation_disabled: false